#!/bin/bash -l

#SBATCH -q defq
#SBATCH -N 1
#SBATCH -n 32
#SBATCH -J japan-project
#SBATCH -o japan-project.%j.out
#SBATCH -e japan-project.%j.error

dataDir=/data/Japan_Project_data/20181219
hostname=$(hostname)
nodeid=$(echo $hostname | cut -c8-9)
jobstxt="jobs$nodeid.txt"
shortMode = 3 # 1 for CO, 3 for Japan and Greenland

./createjobs_adr.sh $dataDir
./AdrParallelRunScript.sh 32 $jobstxt $dataDir $shortMode